# Site settings
name: Draft U.S. Web Design Standards Documentation
version: 0.14.0
permalink: pretty
google_analytics_ua: UA-48605964-43

jekyll_get:
  data: releases
  json: 'https://api.github.com/repos/18F/web-design-standards/releases'

repos:
- name: Draft U.S. Web Design Standards
  description: Main repository for the Draft U.S. Web Design Standards package
  url: https://github.com/18F/web-design-standards
- name: Draft U.S. Web Design Standards Documentation
  description: Documentation for the Draft U.S. Web Design Standards
  url: https://github.com/18F/web-design-standards-docs
- name: Draft U.S. Web Design Standards Assets
  description: Draft U.S. Web Design Standards visual design assets
  url: https://github.com/18F/web-design-standards-assets

sass:
  load_paths:
    - css
    - assets/css

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - with_toc_data # automatic heading ids

gems:
  - jekyll-redirect-from

exclude:
- ".ruby-version"
- ".sass-cache"
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- config
- img
- js
- vendor
- manifest.yml
- node_modules
- package.json
- gulpfile.js
- circle.yml
