version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Display versions
          command: |
            echo ($gulp --version)
            echo ($scss-lint --version)
            echo ($jekyll --version)
      - run:
          name: Build site files
          command: npm run build
      - run:
          name: Run test
          command: npm test
      - run:
          name: Checking build
          command: ls -agolf _site/
